server:
  port: 9090
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: top.cqjokers.sbl.mapper
  configuration:
    call-setters-on-nulls: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbl?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  profiles:
    active: dev